version: '3.8'

networks:
  app-network:

volumes:
  app-data:
  database_scc:

services:
  database_scc:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 4306:3306
    environment:
      MYSQL_ROOT_PASSWORD: manager247
      MYSQL_DATABASE: scc
      MYSQL_USER: arief
      MYSQL_PASSWORD: manager247
      SERVICE_NAME: mysql
    volumes:
      - database_scc:/var/lib/mysql
    networks:
      app-network:
    container_name: db_scc

  website:
    image: php:8.1-fpm
    volumes:
      - ./:/var/www
    working_dir: /var/www
  
  nginx:
    image: nginx:1.21.6-alpine
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80